site_name: Test update Project
pages:
    - "Getting Started": index.md
    - "Documents":
        - "test": test.md
        - "Swagger UI": apex_reserved_swaggerui.md
    - "updated Foo xxx":
        - "updated Foo 1": Foo_1.md
        - "updated Foo 3": Foo_3.md
    - "Other links":
        - "Copyright": copyright.md
        - "Outer links":
                - "Outer links": related_links.md
                - "Splunk dashboard": apex_reserved_splunk_dashboard.md
theme: readthedocs
theme_dir: theme
markdown_extensions:
    - admonition
    - def_list
    - grid_tables
